name: piano_app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.26.4 
  - pillow=11.3.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pip
  - pip:
      - streamlit==1.52.1
      - inference-sdk==0.62.2
      - opencv-python==4.10.0.84
      - supervision==0.27.0
